In [1]:
import numpy as np

In [2]:
def RSA(p,q,key,x,mode):
    n = p*q
    print("n = p x q = ",n) 
    Phi_n = (p-1)*(q-1)
    print("Phi(n) = (p-1) x (q-1) = ",Phi_n)
    key_inverse = pow(key, -1, Phi_n)
    if mode=="encrpt":
        print("the decryption key d ≡ e^(-1) mod Phi(n) = ",key_inverse)
        print("Now,start our encryption process, the plain text is ",x)
        encrypt_text = x**key % n
        print("the encrypt text is, y = x^e mod n = ",encrypt_text)
        print("Now,start our decryption process")
        decrypt_text = encrypt_text**key_inverse % n
        
        print("the decrypt text is, x = y^d mod n = ",decrypt_text)
    else:
        print("the encryption key e ≡ d^(-1) mod Phi(n) = ",key_inverse)
        print("Now,start our encryption process, the plain text is ",x)
        encrypt_text = x**key_inverse % n
        print("the encrypt text is, y = x^e mod n = ",encrypt_text)
        print("Now,start our decryption process")
        decrypt_text = encrypt_text**key % n
        print("the decrypt text is, x = y^d mod n = ",decrypt_text)
    
    

## Question 1
**1.1** p = 3, q = 11, d = 7, x = 5

**1.2** p = 5, q = 11, d = 3, x = 9

In [3]:
#Question 1.1
RSA(3, 11, 7, 5,"decrpt")

n = p x q =  33
Phi(n) = (p-1) x (q-1) =  20
the encryption key e ≡ d^(-1) mod Phi(n) =  3
Now,start our encryption process, the plain text is  5
the encrypt text is, y = x^e mod n =  26
Now,start our decryption process
the decrypt text is, x = y^d mod n =  5


In [4]:
#Question 1.2
RSA(5, 11, 3, 9,"encrpt")

n = p x q =  55
Phi(n) = (p-1) x (q-1) =  40
the decryption key d ≡ e^(-1) mod Phi(n) =  27
Now,start our encryption process, the plain text is  9
the encrypt text is, y = x^e mod n =  14
Now,start our decryption process
the decrypt text is, x = y^d mod n =  9


## Question 2
Compute the two public keys and the common key for the DHKE scheme with the parameters p = 467, α = 2, and

**2.1** a = 3, b = 5

**2.2** a = 400, b = 134

In [5]:
def RSA(p,alpha,a,b):
    print("Alice and Bob agree use p = ", p ,",and alpha = ", alpha ,"as a base.")
    A = alpha**a%p
    print("Alice choose a number a = ", a, ",and calculate the A = alpha^a mod p = ", A ,"and send it to Bob.")
    B = alpha**b%p
    print("Bob choose a number b = ", b, ",and calculate the B = alpha^b mod p = ", B ,"and send it to Alice.")
    K_AB_1 = (B**a)%p
    print("Alice calculate common key K_AB = B^a = ",K_AB_1)
    K_AB_2 = (A**b)%p
    print("Alice calculate common key K_AB = A^b = ",K_AB_2,"as a proof of they match")

In [6]:
#2.1
RSA(467,2,3,5)

Alice and Bob agree use p =  467 ,and alpha =  2 as a base.
Alice choose a number a =  3 ,and calculate the A = alpha^a mod p =  8 and send it to Bob.
Bob choose a number b =  5 ,and calculate the B = alpha^b mod p =  32 and send it to Alice.
Alice calculate common key K_AB = B^a =  78
Alice calculate common key K_AB = A^b =  78 as a proof of they match


In [7]:
#2.2
RSA(467,2,400,134)

Alice and Bob agree use p =  467 ,and alpha =  2 as a base.
Alice choose a number a =  400 ,and calculate the A = alpha^a mod p =  137 and send it to Bob.
Bob choose a number b =  134 ,and calculate the B = alpha^b mod p =  84 and send it to Alice.
Alice calculate common key K_AB = B^a =  90
Alice calculate common key K_AB = A^b =  90 as a proof of they match


 ## Question 3
 Encrypt the following messages with the Elgamal scheme (p = 467 and α = 2):
 
 **3.1** K_pr = d = 105, i = 213, x = 33
 
 **3.2** K_pr = d = 105, i = 123, x = 33
 
 **3.3** K_pr = d = 300, i = 45, x = 248
 
 **3.4** K_pr = d = 300, i = 47, x = 248

In [8]:
def Elgamal_scheme(p,alpha,d,i,x):
    print("Step 1. Bob choose Prime p =",p,",alpha =",alpha,",plain text x =",x)
    
    print("Step 2. Bob has a random number K_pr =",d)
    K_pub = alpha**d%p
    print("Everyone knows the public key between Alice and Bob is K_pub ≡ alpha^d mod p =",K_pub)
    K_E = alpha**i%p
    print("Step 3. Alice will compute a Ephemeral Key K_E ≡ alpha^i mod p =",K_E)
    K_M = K_pub**i%p
    print("Step 4. Alice will also compute a masking Key K_M ≡ K_pub^i mod p =",K_M)
    print("the plaintext was",x)
    y = x*K_M%p
    print("Step 5. Alice encrpts plaintext x with K_M, y ≡ x•K_M mod p =",y,"and send (y,K_E) back to Bob")
    K_M_B = K_E**d%p
    print("Step 6. Bob recovers the K_M by K_M ≡ K_E^d mod p =",K_M_B)
    x_recover = y*pow(K_M,-1,p)%p
    print("Step 7. Bob decrpts the cipher text by x ≡ K_M^(-1)•y =",x_recover)

In [9]:
#3.1
Elgamal_scheme(467,2,105,213,33)

Step 1. Bob choose Prime p = 467 ,alpha = 2 ,plain text x = 33
Step 2. Bob has a random number K_pr = 105
Everyone knows the public key between Alice and Bob is K_pub ≡ alpha^d mod p = 444
Step 3. Alice will compute a Ephemeral Key K_E ≡ alpha^i mod p = 29
Step 4. Alice will also compute a masking Key K_M ≡ K_pub^i mod p = 292
the plaintext was 33
Step 5. Alice encrpts plaintext x with K_M, y ≡ x•K_M mod p = 296 and send (y,K_E) back to Bob
Step 6. Bob recovers the K_M by K_M ≡ K_E^d mod p = 292
Step 7. Bob decrpts the cipher text by x ≡ K_M^(-1)•y = 33


In [10]:
#3.2
Elgamal_scheme(467,2,105,123,33)

Step 1. Bob choose Prime p = 467 ,alpha = 2 ,plain text x = 33
Step 2. Bob has a random number K_pr = 105
Everyone knows the public key between Alice and Bob is K_pub ≡ alpha^d mod p = 444
Step 3. Alice will compute a Ephemeral Key K_E ≡ alpha^i mod p = 125
Step 4. Alice will also compute a masking Key K_M ≡ K_pub^i mod p = 278
the plaintext was 33
Step 5. Alice encrpts plaintext x with K_M, y ≡ x•K_M mod p = 301 and send (y,K_E) back to Bob
Step 6. Bob recovers the K_M by K_M ≡ K_E^d mod p = 278
Step 7. Bob decrpts the cipher text by x ≡ K_M^(-1)•y = 33


In [11]:
#3.3
Elgamal_scheme(467,2,300,45,248)

Step 1. Bob choose Prime p = 467 ,alpha = 2 ,plain text x = 248
Step 2. Bob has a random number K_pr = 300
Everyone knows the public key between Alice and Bob is K_pub ≡ alpha^d mod p = 317
Step 3. Alice will compute a Ephemeral Key K_E ≡ alpha^i mod p = 80
Step 4. Alice will also compute a masking Key K_M ≡ K_pub^i mod p = 12
the plaintext was 248
Step 5. Alice encrpts plaintext x with K_M, y ≡ x•K_M mod p = 174 and send (y,K_E) back to Bob
Step 6. Bob recovers the K_M by K_M ≡ K_E^d mod p = 12
Step 7. Bob decrpts the cipher text by x ≡ K_M^(-1)•y = 248


In [12]:
#3.4
Elgamal_scheme(467,2,300,47,248)

Step 1. Bob choose Prime p = 467 ,alpha = 2 ,plain text x = 248
Step 2. Bob has a random number K_pr = 300
Everyone knows the public key between Alice and Bob is K_pub ≡ alpha^d mod p = 317
Step 3. Alice will compute a Ephemeral Key K_E ≡ alpha^i mod p = 320
Step 4. Alice will also compute a masking Key K_M ≡ K_pub^i mod p = 74
the plaintext was 248
Step 5. Alice encrpts plaintext x with K_M, y ≡ x•K_M mod p = 139 and send (y,K_E) back to Bob
Step 6. Bob recovers the K_M by K_M ≡ K_E^d mod p = 74
Step 7. Bob decrpts the cipher text by x ≡ K_M^(-1)•y = 248


## Question 4
Considering the four examples from Problem 4.1, we see that the Elgamal scheme is nondeterministic: A given plaintext x has many valid ciphertext, e.g., both x = 33 and x = 248 have the same ciphertext in the problem above.

**4.1** Why is the Elgamal signature scheme nondeterministic?

**4.2** How many valid ciphertexts exist for each message x (general expression)?
How many are there for the system in Problem 4.3.1 (numerical answer)?

**4.3** Is RSA crypto system nondeterministic once the public key has been chosen?

**Answer of 4.1**

In this context, "nondeterministic" means that the algorithm to generate the ciphertext (or the signature) takes a random value as one of its inputs, and it can generate many possible ciphertexts (or signatures) based on the random value. ElGamal is nondetermanistic because the encryptor selects a random exponent as a part of encryption method.

For public key encryption, this randomization of the encrypted message is important. If the public key encryption algorithm was not nondetermistic (that is, the encrypted message depended only on the plaintext message and the public key), then someone with an encrypted message M and the public key $PK$ and a candidate plaintext message P could test if the decryption of M was P (simply by encrypting P using the public key $PK$, and checking if the result was M).

Because of this, public key encryption is almost always nondetermanistic.

**Answer of 4.2**

It depends on how many space ring $p$, In general, we could have $(2,3,\dots,p-2)$ choice of cipher text, which has $p-3$ different valid cipher text options. However, Once we set up our $k_{pr}$, the cipher text choices could be limited by $k_{pr}$ and $p$


**Answer of 4.3**

The RSA encryption system is deterministic. Once the public parameter has set up, a plain text will always be encrypted to a fixed cipher text.

 ## Question 5
Given EC: 
 
$$ E: 𝑦^2≡ 𝑥^3+2𝑥+2 \quad mod \ 17 $$

All points on the curve form a cyclic group and that the order is #E = 19. The base point/primitive element is $𝑃=(5,1)$, please calculate $2P, 3P, 4P, 5P, 6P, 7P, 8P, 9P, 10P, 11P, 12P, 13P, 14P, 15P, 16P, 17P, 18P$ and $19P$.

In [17]:
def EC_add(P,Q,p,a,b):
    if P==Q:
        s = ((3 * P[0]**2 + a)*pow(2 * P[1] , -1 , p ) )%p
    else: 
        s = ((Q[1] - P[1])*pow(Q[0] - P[0] , -1 , p ) )%p

    x = (s**2 - P[0] - Q[0]) % p    
    
    temp = (s * (P[0] - x) - P[1]) % p
    
    if (temp**2%p == (x**3 + 2 * x + 2) % p):
        y = temp
        print("the calculated y is on the curve")
    else:
        y = temp-p
        print("the calculated y is not on the curve, it is on the negative plane")
    print("the final answer is","(",x,",",y,")")
    
    return (x,y)

In [18]:
P1 = (5,1)
p = 17
a = 2
b = 2

In [19]:
P_increment = P1
for i in range(2,19):
    print("For",i,"P, The answer of location is:")
    P_increment = EC_add(P_increment,P1,p,a,b)
print("For 19 P, The answer of location is special 0 ")   

For 2 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 6 , 3 )
For 3 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 10 , 6 )
For 4 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 3 , 1 )
For 5 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 9 , 16 )
For 6 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 16 , 13 )
For 7 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 0 , 6 )
For 8 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 13 , 7 )
For 9 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 7 , 6 )
For 10 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 7 , 11 )
For 11 P, The answer of location is:
the calculated y is on the curve
the final answer is ( 13 , 10 )


In [21]:
6**7*7**5%11

3

In [24]:
6**7*7**5

4704884352

In [22]:
3**5%11

1

In [23]:
3**5

243